"""added new_script_column

Revision ID: 0353ec7da98a
Revises: 2debc503c6a6
Create Date: 2024-06-12 16:03:38.996729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0353ec7da98a'
down_revision = '2debc503c6a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_script_column', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('new_script_column')

    # ### end Alembic commands ###
