"""drop column mobile

Revision ID: 199ab9eb49be
Revises: a615f8a60bd3
Create Date: 2024-06-13 10:46:07.516523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199ab9eb49be'
down_revision = 'a615f8a60bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('mobile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.VARCHAR(length=256), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
