"""added another_column_3

Revision ID: 4ec23e9ce420
Revises: a6bf58aefb5a
Create Date: 2024-06-13 10:41:39.311910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec23e9ce420'
down_revision = 'a6bf58aefb5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('another_column_3', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('another_column_3')

    # ### end Alembic commands ###
