"""new_column_main added

Revision ID: 550d4df432f1
Revises: 4f644ab9721b
Create Date: 2024-06-13 10:43:10.250516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550d4df432f1'
down_revision = '4f644ab9721b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_column_main', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('new_column_main')

    # ### end Alembic commands ###
