"""another_column_2

Revision ID: 6e029a13c3e3
Revises: 2debc503c6a6
Create Date: 2024-06-12 16:01:59.312205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e029a13c3e3'
down_revision = '2debc503c6a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('another_column_2', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('another_column_2')

    # ### end Alembic commands ###
