"""add new_column_main

Revision ID: 7a5e8fafd11b
Revises: 0b1103401e36
Create Date: 2024-06-12 10:41:29.882036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5e8fafd11b'
down_revision = '0b1103401e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('another_column', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('new_column_main', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('new_column_main')
        batch_op.drop_column('another_column')

    # ### end Alembic commands ###
