"""added new new_script_column

Revision ID: ba3888f06f48
Revises: 0b1103401e36
Create Date: 2024-06-12 10:39:55.940231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3888f06f48'
down_revision = '0b1103401e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('another_column', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('new_script_column', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('new_script_column')
        batch_op.drop_column('another_column')

    # ### end Alembic commands ###
