name: Get Changed Files

on: 
  push:
    branches:
      - master  # Change to your branch name

jobs:
  list-changed-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Get list of changed files
      id: changed-files
      run: |
        # Fetch the previous commit SHA
        PREV_SHA=$(git rev-parse HEAD^1)
        # Get the current commit SHA
        CURRENT_SHA=$(git rev-parse HEAD)
        # List files changed in the push
        git diff --name-only $PREV_SHA $CURRENT_SHA > changed_files.txt
        cat changed_files.txt

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask Flask-Migrate psycopg2-binary

    - name: show heads of the database
      run: |
          flask db heads

    - name: Run Python script
      run: python merge_migration.py

    - name: Delete head count file
      run: rm changed_files.txt

    - name: Merge migrations if multiple heads
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add migrations/versions/
        git commit -m 'Auto-merge migrations'
        git push origin master