name: Merge Flask Migrations

on:
    push:
        branches:
            - master

jobs:
    merge-migrations:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install Flask Flask-Migrate
                - name: Merge migrations
                run: |
                  flask db merge heads -m "Merge migrations"
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
                  git add migrations/versions/
                  git commit -m 'Auto-merge migrations'
                  git push origin master 